metadata:
  creationTimestamp: null
  name: deploy-key
  namespace: flux-system
stringData:
  identity.pub: |
    -----BEGIN PUBLIC KEY-----
    MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAECxKe91S84l24SnIwpTtW0RtyMQ01Uc3q
    exUt/apWo6xWkxeusmyHPyG5xMel31KPl0cG/jXvw4REXXmKXUl3uSCScMmWaP7C
    e/qHUlhFexlyNT0gtjtmh4M1wjiChBMU
    -----END PUBLIC KEY-----
  known_hosts: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
  private.key: |
    -----BEGIN ECDSA PRIVATE KEY-----
    MIGkAgEBBDDpzssbp7NpUM+Teexa0mrnyv1m1mZ3V9YEoo31QSWo7z897W7d/yDa
    bL9tjBzkwrSgBwYFK4EEACKhZANiAAQLEp73VLziXbhKcjClO1bRG3IxDTVRzep7
    FS39qlajrFaTF66ybIc/IbnEx6XfUo+XRwb+Ne/DhERdeYpdSXe5IJJwyZZo/sJ7
    +odSWEV7GXI1PSC2O2aHgzXCOIKEExQ=
    -----END ECDSA PRIVATE KEY-----
type: Opaque
